name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: davidgieseler
          outputs: |
            dist/github-grid-snake.svg
            dist/github-grid-snake-dark.svg
          
          # Configurações de cores personalizadas
          color_snake: "C77DFF"            # Cobra roxa neon
          color_dots: |
            "#0D1117"                      # Fundo neutro escuro
            "#FFA500"                      # Laranja (cor que lembra comida para commits)
            "#4C3A51"                      # Roxo escuro para variação de fundo
            "#C77DFF"                      # Roxo claro para variedade
          
          # Configurações para o crescimento da cobra
          snake_animations: |
            growing_snake
          bg_color: "#0D1117"              # Fundo escuro personalizado
          snake_size: 2                    # Tamanho inicial da cobra
          max_snake_length: 20             # Comprimento máximo ajustado
          snake_growth_scale: 1.5          # Taxa de crescimento aumentada para mais visibilidade

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
