name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: davidgieseler
          outputs: |
            dist/github-grid-snake.svg
            dist/github-grid-snake-dark.svg
          
          # Configurações aprimoradas
          color_snake: "C77DFF"            # Cobra em roxo neon
          color_dots: |
            "#161B22"                      # Fundo escuro do GitHub
            "#4C3A51"                      # Roxo escuro
            "#9D4EDD"                      # Roxo médio
            "#C77DFF"                      # Roxo claro
            "#E0AAFF"                      # Roxo mais claro
          
          # Configurações para a cobra crescer
          snake_animations: |
            growing_snake
          bg_color: "#0D1117"             # Fundo escuro personalizado
          snake_size: 2                    # Tamanho inicial da cobra
          max_snake_length: 15             # Comprimento máximo
          snake_growth_scale: 1.2          # Taxa de crescimento após comer

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
